global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ingestion-service'
    static_configs:
      - targets: ['ingestion-service:8080']

  - job_name: 'drift-engine'
    static_configs:
      - targets: ['drift-engine:7070']

  - job_name: 'llm-guard'
    static_configs:
      - targets: ['llm-guard:8000']

